# Generated by Django 5.0.1 on 2024-08-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_sizes_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variations',
            field=models.BooleanField(default=True),
        ),
    ]
