# Generated by Django 5.0.1 on 2024-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_remove_homepagebannerstwo_title_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorypagebanner',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='categorypagebanner',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='categorypagebanner',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='createyourownpagesbanners',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='createyourownpagesbanners',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='createyourownpagesbanners',
            name='title_3',
        ),
        migrations.RemoveField(
            model_name='shopallpagesbanners',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='shopallpagesbanners',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='shopallpagesbanners',
            name='title_3',
        ),
        migrations.AddField(
            model_name='categorypagebanner',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='createyourownpagesbanners',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='shopallpagesbanners',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
