# Generated by Django 5.0.1 on 2024-06-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_childcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcategory',
            name='home',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
