# Generated by Django 5.0.1 on 2024-08-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customkit', '0015_customcolor_customfonts_footerlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customorder',
            name='sizes',
        ),
        migrations.AddField(
            model_name='customorder',
            name='sizes_l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customorder',
            name='sizes_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customorder',
            name='sizes_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customorder',
            name='sizes_xl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customorder',
            name='sizes_xxl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customorder',
            name='sizes_xxxl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
