# Generated by Django 5.0.1 on 2024-08-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customkit', '0017_alter_footerlink_allclasses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfonts',
            name='google_fonts_link',
        ),
        migrations.AddField(
            model_name='customfonts',
            name='font_file',
            field=models.FileField(default='', upload_to='fonts/'),
            preserve_default=False,
        ),
    ]
